### ISSUE TITLE
To Do

### ISSUE THREAD

**Issue by 0xddom** [KuroAku/flink#1]
¿De la parte que está en tu commit esta todo terminado?

Aparte de eso quedaría la parte de los accidentes y asegurar que el paralelismo funcione bien con 10 nodos.

¿Me dejo algo?

**Comment by JTL1992** [comment]
estoy con la parte de de los accidentes ya, creo que más o menos lo tengo, solo falta el paralelismo.

**Comment by 0xddom** [comment]
Nice nice.

¿Como estas haciendo la parte de los accidentes? Brian me dijo que con una Sliding Window se hace muy facil.

**Comment by JTL1992** [comment]
Como estamos usando DataSet no DataStream, no uso Sliding Window, pero con groupBy y sortGroup, se puede obtener datos de coches con timestamp ordenado, y hago reduce sobre los grupos para tener Accidents con tiempo seguido, entonces, al final se hace un FlatMap para separarlo con el hueco de tiempo de 90 segundos para cada evento.

**Comment by 0xddom** [comment]
Miro yo esta tarde lo del paralelismo y hago unas pruebas
